tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "automake"
brew "ffmpeg"
brew "git"
brew "grep"
brew "imagemagick"
brew "jq"
brew "mas"
brew "nano"
brew "ncdu"
brew "ninja"
brew "node"
brew "pyenv"
brew "rbenv"
brew "thefuck"
brew "tree"
brew "vim"
brew "wget"
brew "youtube-dl"
cask "1password"
cask "alfred"
cask "audirvana"
cask "discord"
cask "firefox"
cask "font-fira-code"
cask "iina"
cask "logitech-options"
cask "netnewswire"
cask "slack"
cask "sublime-text"
cask "tiles"
cask "tower"
cask "transmission"
cask "whatsapp"
mas "1Blocker", id: 1107421413
mas "Amphetamine", id: 937984704
mas "StopTheMadness", id: 1376402589
mas "ToothFairy", id: 1191449274
mas "Twitter", id: 1482454543
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
